# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Wilbur
# tagline:             I have no tagline — i am me
url:                 wilburc.github.io
paginate:            100
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

#Pages for Nav
nav_items:
  About: /about/
  Projects: /projects/
  Writing: /writing/
  Resumé: /files/wilbur_chen_resume.pdf


#Work
collections:
- portfolio

collections:
  portfolio:
    output: true

# About/contact
author:
  name:              Wilbur Chen
  url:               https://twitter.com/wilbtweet
  email:             wilburchen1@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/wilburc/wilburc.github.io

# Gems

gems: [jekyll-paginate]
gems: [jekyll-gist]